INSERT INTO subject (name, lecturer_full_name)
VALUES ('Matematyka Dyskretna', 'Jan Kowalski'),
       ('Analiza Matematyczna', 'Anna Nowak'),
       ('Programowanie Obiektowe', 'Piotr Wiśniewski'),
       ('Fizyka Eksperymentalna', 'Maria Lewandowska'),
       ('Wstęp do Informatyki', 'Krzysztof Zieliński'),
       ('Algorytmy i Struktury Danych', 'Łukasz Kaczmarek'),
       ('Bazy Danych', 'Magdalena Piotrowska'),
       ('Sieci Komputerowe', 'Rafał Jankowski'),
       ('Architektura Komputerów', 'Monika Szymańska'),
       ('Teoria Automatyka', 'Wojciech Mazur'),
       ('Inżynieria Oprogramowania', 'Zofia Wojciechowska'),
       ('Podstawy Sztucznej Inteligencji', 'Katarzyna Kowalczyk'),
       ('Wykład z Matematyki', 'Piotr Tomaszewski'),
       ('Chemia Fizyczna', 'Adam Wysocki'),
       ('Logika Matematyczna', 'Ewa Nowicka'),
       ('Programowanie w Pythonie', 'Jacek Ślusarczyk'),
       ('Bezpieczeństwo Sieci', 'Aleksandra Woźniak'),
       ('Sztuczna Inteligencja', 'Kamil Król'),
       ('Zarządzanie Projektami IT', 'Tomasz Chmielowski'),
       ('Optymalizacja', 'Sławomir Pawlak'),
       ('kokonik', 'Krak'),
       ('kot', 'Krak');
