INSERT INTO subject (name, lecturer_full_name, semester)
VALUES ('Matematyka Finansowa', 'Michał Dąbrowski', 2),
       ('Teoria Grafów', 'Zuzanna Nowakowska', 2),
       ('Sieci Wirtualne', 'Wojciech Ślusarski', 2),
       ('Algorytmy Wyszukiwania', 'Paweł Jasiński', 2),
       ('Systemy Operacyjne', 'Marcin Kowalczyk', 2),
       ('Technologie Webowe', 'Sylwia Nowak', 2),
       ('Programowanie w C++', 'Robert Król', 2),
       ('Teoria Gier', 'Julia Wiśniewska', 2),
       ('Matematyka Wyższa', 'Ewa Zielińska', 2),
       ('Sztuczna Inteligencja w Praktyce', 'Jakub Kowalski', 2),
       ('Bazy Danych zaawansowane', 'Dorota Majewska', 2),
       ('Inżynieria Wyszukiwarek', 'Tomasz Chmielowski', 2),
       ('Przetwarzanie Obrazów', 'Krzysztof Bąk', 2),
       ('Wprowadzenie do Big Data', 'Monika Woźniak', 2),
       ('Programowanie w Java', 'Anna Lisowska', 2),
       ('Nowoczesne Technologie Programistyczne', 'Patryk Kowalski', 2),
       ('Rynki Finansowe i Algorytmy', 'Janusz Nowak', 2),
       ('Metody Numeryczne', 'Kamil Wojciechowski', 3),
       ('Optymalizacja w IT', 'Agnieszka Kowalczyk', 3),
       ('Zarządzanie Bazami Danych', 'Marek Piotrowski', 4);